config/routes.rb
Rails.application.routes.draw do
  get 'game' => 'longest_words#game'

  get 'score' => 'longest_words#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/longest_words_controller.rb
require 'open-uri'
require 'json'
require 'pry-byebug'

class LongestWordsController < ApplicationController



  def game
    @grid = generate_grid(10).join(" ")
    @start_time = Time.now
  end

  def score
    @end_time = Time.now
    @start_time = Time.parse(params[:start_time])
    @result = run_game(params[:word], params[:grid], @start_time, @end_time)
  end

  private


  def generate_grid(grid_size)
    # TODO: generate random grid of letters
    grid = (0...grid_size).map { ('a'..'z').to_a[rand(26)] }
  end

  def run_game(attempt, grid, start_time, end_time)
    # TODO: runs the game and return detailed hash of result
    # On cree un hash ou on va tout stocker
    # 1 - On check si attempt est dans la grille et en anglais et on recupere la traduction
    result = translation(attempt, grid)

    # Add infos inside the hash
    result[:score] = result[:score].fdiv(end_time - start_time)
    result[:time] = end_time - start_time

    return result
  end

  def translation(attempt, grid)
    result = {}
    attempt_a = attempt.split("") # passe le attempt en array
    if attempt_a.all? { |letter| grid.include?(letter) }
      # Si le mot est dans la grille on check la traduction
      url = "https://api-platform.systran.net/translation/text/translate?input=#{attempt}&source=auto&target=fr&withSource=false&withAnnotations=false&backTranslation=false&encoding=utf-8&key=2fce6a6e-af77-4840-921d-5dbbe3df9efd"
      begin
        traduction_api = JSON.parse(open(url).read)
      rescue
        # si le mot existe == traduction ok
         result[:message] = "Ce n'est pas un mot de la langue anglaise"
         result[:translation] = "N/a"
         result[:score] = 0
      else
         result[:translation] = traduction_api["outputs"][0]["output"]
         result[:message] = "Bien joué !"
         result[:score] = 1
      end
    else
       result[:message] =  "Ce mot n'est pas présent dans la grille"
       result[:translation] = "N/A"
       result[:score] = 0
    end
    result
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/longest_words_helper.rb
module LongestWordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/longest_words/game.html.erb
<h1>LongestWords#game</h1>
<h2>Les lettres tirées au sort</h2>
<h2><%= @grid %></h2>
<form action="/score">
  <input type="hidden" name="grid" value="<%= @grid %>">
  <input type="hidden" name="start_time" value="<%= @start_time %>">
  <input type="text" name="word" placeholder="Type your best guess">
  <input type="submit">
</form>

app/views/longest_words/score.html.erb
<h1>LongestWords#score</h1>
<p>Find me in app/views/longest_words/score.html.erb</p>

<h1>Résultat !</h1>
<p><%= @result[:message] %>
</p>
<h1>Traduction</h1>
<p><%= @result[:translation] %>
</p>
<h1>Time</h1>
<p><%= @result[:time] %>
</p>
<h1>Score</h1>
<p><%= @result[:score] %>
</p>

<p>
  <%= link_to "Générer une nouvelle grille", game_path %>
</p>